### ISSUE TITLE
Gamemode not starting

### ISSUE THREAD

**Issue by SupperCraft5000** [Stuyk/altV-Fuel-Rats#1]
```
[12:56:55] alt:V Server, build #1181, branch release
[12:56:56] Starting alt:V Server on 0.0.0.0:7788
[12:56:56] Loading resource fuelrats
G:\altv-test-server\resources\fuelrats\server\startup.js:1
import * as alt from 'alt';
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at internal/modules/esm/translators.js:100:15
    at Object.meta.done (internal/modules/esm/create_dynamic_module.js:48:9)
    at file:///G:/altv-test-server/resources/fuelrats/server/startup.js:9:13
    at ModuleJob.run (internal/modules/esm/module_job.js:111:37)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Loader.import (internal/modules/esm/loader.js:131:24)
[12:56:56][Error] Failed to load resource fuelrats
[12:56:56] Starting HTTP server on 0.0.0.0:7788
[12:56:56] Server started
```
![Unbenannt](https://user-images.githubusercontent.com/17689259/87779524-336bae80-c82d-11ea-8e10-4ea65695a9df.PNG)

**Comment by Stuyk** [comment]
NodeJS 13+
